Workshop 01: Numpy

In [1]:
import numpy as np

In [2]:
R = np.array([
    [1,5,5,0,3],
    [2,0,5,0,3],
    [0,0,0,0,0],
    [2,0,0,4,0],
    [0,4,2,0,0]
])

In [3]:
T = np.array([
    [0,2,4,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,4,3],
    [0,2,5,0,0]
])

In [4]:
L = np.array([
    [2,5,1,0,3],
    [0,0,0,0,0],
    [0,5,0,3,3],
    [1,0,0,4,1],
    [0,0,9,0,0]
])

Engagement Statics

In [5]:
R

array([[1, 5, 5, 0, 3],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [6]:
# Find the user who replies more than others
np.argmax(R.sum(axis=1))

np.int64(0)

In [7]:
# Find the user who retweets more than others
np.argmax(T.sum(axis=1))

np.int64(3)

In [8]:
# . Find users who replied or retweeted at least once
np.where(R.sum(axis=1) + T.sum(axis=1) > 1)

(array([0, 1, 3, 4]),)

In [9]:
# Display the number of likes each user has given to their own tweets
np.diag(L)

array([2, 0, 0, 4, 0])

In [10]:
# Display the number of likes each user has given to tweets other than their own
L.sum(axis=1) - np.diag(L)

array([ 9,  0, 11,  2,  9])

In [11]:
# Find users who gave likes to their own tweets more than they gave to others
np.where(np.diag(L)> (L.sum(axis=1) - np.diag(L)))[0]

array([3])

In [12]:
#  Count users who gave likes to their own tweets more than they gave to others
np.sum(np.diag(L)> ((L.sum(axis=1) - np.diag(L))))

np.int64(1)

In [13]:
(R+T+L).sum(axis=1)

array([31, 10, 11, 19, 22])

Interaction Statistics

In [14]:
# Display the maximum number of likes each user has received (from users other than themselves)
mask = 1 - np.eye(5, dtype=int)
np.max(L * mask, axis=0)

array([1, 5, 9, 3, 3])

In [15]:
# Find users who have received likes for all their tweets by at least one person other than themselves
P = np.array([
    [2,5,10,4,3],
])

In [16]:
L_non_diag = L * mask
Likes_from_others = L_non_diag.sum(axis=0)
Likes_from_others

array([ 1, 10, 10,  3,  7])

In [17]:
np.where(Likes_from_others >= P)

(array([0, 0, 0]), array([1, 2, 4]))

In [18]:
# Calculate the number of incoming edges
incoming_edges = np.sum((R+T+L)>0, axis=0)
incoming_edges

array([3, 3, 3, 2, 4])

In [19]:
# Calculate the number of outgoing edges
outgoing_edges = np.sum((R+T+L)>0, axis=1)
outgoing_edges 

array([4, 3, 3, 3, 2])

In [20]:
# Find nodes where the number of incoming edges is equal to the number of outgoing edges
np.where(incoming_edges == outgoing_edges)[0]

array([1, 2])

In [25]:
# Display the likes they have given to each other
L[np.ix_([1,2],[2,1])]

array([[0, 0],
       [0, 5]])

Popularity